### ISSUE TITLE
Home Surveillance hides Smart Homes

### ISSUE THREAD

**Issue by qayshp** [antievictionmappingproject/landlordtech#2]
On the page, clicking to expand either of the two always gets the values for Surveillance.

Looking at the js, you'll find that the id 4 is repeated, so one is picked over the other.

id: 4,
    type: "direct",
    title: "Smart Homes",

id: 4,
    type: "direct",
    title: "Home Surveillance",

**Comment by wonyoungso** [comment]
Thanks for reporting! I just fixed the id.
